spring.application.name=enterCamel
spring.application.description=Enter Camel Application
server.port=8080
spring.application.version=0.0.1-SNAPSHOT
management.endpoint.health.probes.enabled=true
camel.springboot.main-run-controller=true
camel.rest.component=platform-http
weather.geocoding-url=https://geocoding-api.open-meteo.com
weather.forecast-url=https://api.open-meteo.com
